# Read the Docs configuration file for PyDevelop-Docs
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install poetry for dependency management
      - pip install poetry
    post_install:
      # Install project dependencies with poetry
      - poetry config virtualenvs.create false
      - poetry install --with docs
  apt_packages:
    # Required for some Sphinx extensions
    - graphviz
    - graphviz-dev
    - plantuml
    - imagemagick
    - pandoc

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

formats:
  - pdf
  - epub

search:
  ranking:
    api/index.html: -1
  ignore:
    - search.html
    - 404.html
    - "_autoapi_templates/*"
    - "_modules/*"
    - "_sources/*"