[tool.poetry]
name = "testhaive-core"
version = "0.1.0"
description = "Core framework components (mimics haive-core structure)"
authors = ["Test <test@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.packages]
packages = [{ include = "testhaive", from = "src" }]
