# Generated Sphinx Configuration
# Auto-generated by PyAutoDoc ConfigLoader
# DO NOT EDIT MANUALLY - Edit YAML files instead

import os
import sys

from sphinx.application import Sphinx

# Path setup
sys.path.insert(0, os.path.abspath("../../src"))

# Project information
project = "pyautodoc"
author = "William R. Astley"
copyright = "2025, William R. Astley"
release = "0.1.0"

# Extensions
extensions = [
    "sphinx.ext.autodoc",
    "autoapi.extension",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinxcontrib.autodoc_pydantic",
    "enum_tools.autoenum",
    "sphinx_autodoc_typehints",
    "myst_parser",
    "sphinx_design",
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "sphinx_tabs.tabs",
    "sphinx.ext.graphviz",
    "sphinxcontrib.mermaid",
    "sphinxcontrib.plantuml",
]

# General configuration
templates_path = ["_templates", "_autoapi_templates"]
html_static_path = ["_static"]
exclude_patterns = []
add_module_names = False
toc_object_entries_show_parents = "hide"

# Jinja2 options
jinja_env_options = {"extensions": ["jinja2.ext.do"]}

autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
}
autoapi_type = "python"
autoapi_dirs = ["../../../src"]
autoapi_template_dir = "_autoapi_templates"
autoapi_add_toctree_entry = True
autoapi_generate_api_docs = True
autoapi_keep_files = True
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
    "private-members",
    "special-members",
    "imported-members",
]
autoapi_python_class_content = "both"
autoapi_add_class_diagram = True
autoapi_class_diagram_depth = 2
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
intersphinx_mapping = {
    "python": ["https://docs.python.org/3", None],
    "pydantic": ["https://docs.pydantic.dev/latest", None],
    "sphinx": ["https://www.sphinx-doc.org/en/master", None],
}
autodoc_pydantic_model_show_json = True
autodoc_pydantic_model_show_config_summary = True
autodoc_pydantic_model_show_validator_summary = True
autodoc_pydantic_model_show_field_summary = True
autodoc_pydantic_model_show_validator_members = True
autodoc_pydantic_field_list_validators = True
autodoc_pydantic_field_show_constraints = True
autodoc_pydantic_model_erdantic_figure = True
autodoc_pydantic_model_erdantic_figure_collapsed = False
typehints_fully_qualified = False
typehints_use_signature = True
myst_enable_extensions = [
    "deflist",
    "tasklist",
    "html_image",
    "colon_fence",
    "smartquotes",
    "replacements",
    "linkify",
    "strikethrough",
    "attrs_inline",
    "attrs_block",
]
myst_heading_anchors = 3
myst_fence_as_directive = ["mermaid", "note", "warning"]
sd_fontawesome_latex = True
togglebutton_hint = "Click to expand"
togglebutton_hint_hide = "Click to collapse"
copybutton_prompt_text = (
    ">>> |\\.\\.\\. |\\$ |In \\[\\d*\\]: | {2,5}\\.\\.\\.: | {5,8}: "
)
copybutton_prompt_is_regexp = True
copybutton_remove_prompts = True
sphinx_tabs_disable_tab_closing = True
mermaid_params = [
    "--theme",
    "neutral",
    "--width",
    "800",
    "--backgroundColor",
    "transparent",
]
mermaid_verbose = True
mermaid_cmd = "mmdc"
plantuml_output_format = "svg"
plantuml = "plantuml"

# Theme configuration
html_theme = "furo"
html_theme_options = {
    "sidebar_hide_name": False,
    "light_css_variables": {
        "color-brand-primary": "#2563eb",
        "color-brand-content": "#1d4ed8",
        "color-background-primary": "#ffffff",
        "color-background-secondary": "#f8fafc",
        "color-background-hover": "#e2e8f0",
        "color-background-border": "#cbd5e1",
        "color-code-background": "#1e293b",
        "color-code-foreground": "#e2e8f0",
        "color-sidebar-background": "#0f172a",
        "color-sidebar-foreground": "#cbd5e1",
        "color-sidebar-item-background--current": "#1e40af",
        "color-sidebar-item-background--hover": "#1e293b",
        "color-api-background": "#f1f5f9",
        "color-api-background-hover": "#e2e8f0",
        "color-admonition-background": "#dbeafe",
    },
    "dark_css_variables": {
        "color-brand-primary": "#60a5fa",
        "color-brand-content": "#3b82f6",
        "color-background-primary": "#0f172a",
        "color-background-secondary": "#1e293b",
        "color-background-hover": "#334155",
        "color-background-border": "#475569",
        "color-code-background": "#0f172a",
        "color-code-foreground": "#cbd5e1",
        "color-sidebar-background": "#020617",
        "color-sidebar-foreground": "#94a3b8",
        "color-sidebar-item-background--current": "#1d4ed8",
        "color-sidebar-item-background--hover": "#1e293b",
    },
    "source_repository": "https://github.com/yourusername/pyautodoc/",
    "source_branch": "main",
    "source_directory": "docs/",
    "announcement": '🚀 <strong>PyAutoDoc 0.1.0</strong> - Hyper-organized documentation with intense Furo theming!\n<a href="/changelog/">See what\'s new →</a>\n',
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/yourusername/pyautodoc/",
            "html": '<svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16">\n  <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>\n</svg>\n',
        }
    ],
}
html_css_files = ["css/furo-intense.css", "css/api-docs.css", "css/mermaid-custom.css"]
html_js_files = ["js/furo-enhancements.js", "js/mermaid-config.js"]


# Event Hooks
def autoapi_skip_member(app, what, name, obj, skip, options):
    if name.startswith("__pydantic"):
        return True
    return None


def setup(app: Sphinx):
    app.connect("autoapi-skip-member", autoapi_skip_member)
