"""
Sphinx configuration for testhaive-core.
Generated by pydvlppy with AutoAPI hierarchical organization.

✅ INCLUDES AUTOAPI HIERARCHICAL FIX - Issue #4 Solution
This configuration automatically applies the validated solution that transforms
flat alphabetical API listings into organized hierarchical structure.
"""

import os
import sys

# Path setup
sys.path.insert(0, os.path.abspath("../.."))

# Import pydvlppy configuration with hierarchical AutoAPI fix
try:
    from pydevelop_docs.config import get_haive_config

    config = get_haive_config(
        package_name="testhaive-core", package_path="../..", is_central_hub=False
    )
    # ✅ This config includes autoapi_own_page_level="module" for hierarchical organization
    globals().update(config)
except ImportError:
    # Fallback to embedded configuration

    project = "testhaive-core"
    extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon"]
    html_theme = "furo"
