[tool.poetry]
name = "testhaive-tools"
version = "0.1.0"
description = "Tool implementations (mimics haive-tools structure)"
authors = ["Test <test@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.packages]
packages = [{ include = "testhaive", from = "src" }]
